package main

import (
	"log"

	"github.com/redis/go-redis/v9"

	"theraclosure/payments-service/internal/adapters/config"
	"theraclosure/payments-service/internal/adapters/http"
	"theraclosure/payments-service/internal/adapters/logging"
	"theraclosure/payments-service/internal/adapters/monitoring"
	"theraclosure/payments-service/internal/adapters/persistence"
	"theraclosure/payments-service/internal/adapters/stripe"
	"theraclosure/payments-service/internal/core/services"
	_ "theraclosure/payments-service/docs" // This will be generated by swag
)

// @title           Payments Service API
// @version         1.0
// @description     A comprehensive payments service built with Go, providing customer management, subscription handling, and Stripe integration.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.theraclosure.com/support
// @contact.email  support@theraclosure.com

// @license.name  MIT
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:3004
// @BasePath  /api/v1

// @securityDefinitions.basic  BasicAuth

// @externalDocs.description  OpenAPI
// @externalDocs.url          https://swagger.io/resources/open-api/

func main() {
	// Load configuration
	cfg, err := config.LoadConfig()
	if err != nil {
		log.Fatalf("Failed to load config: %v", err)
	}

	// Initialize structured logger
	logger := logging.NewLogger(cfg.App.LogLevel)
	logger.WithFields(logging.Fields{
		{Key: "service", Value: cfg.App.Name},
		{Key: "version", Value: cfg.App.Version},
	}).Info("Starting payments service")

	// Initialize monitoring
	metrics := monitoring.NewMetrics(cfg.App.Name, cfg.App.Version)
	logger.Info("Monitoring system initialized")

	// Initialize database
	db, err := persistence.NewDatabase(cfg)
	if err != nil {
		log.Fatalf("Failed to initialize database: %v", err)
	}

	// Initialize database monitoring
	_ = monitoring.NewDatabaseMonitor(db.GetDB(), metrics)
	logger.Info("Database monitoring initialized")

	// Initialize repositories
	customerRepo := persistence.NewCustomerRepository(db)
	subscriptionRepo := persistence.NewSubscriptionRepository(db)
	paymentRepo := persistence.NewPaymentRepository(db)

	// Initialize Redis client (optional)
	var redisClient *redis.Client
	if cfg.Redis.Address != "" {
		redisClient = redis.NewClient(&redis.Options{
			Addr:     cfg.Redis.Address,
			Password: cfg.Redis.Password,
			DB:       cfg.Redis.DB,
		})
		_ = monitoring.NewRedisMonitor(metrics)
		logger.Info("Redis client and monitoring initialized")
	} else {
		logger.Info("Redis not configured, health checks will show degraded status")
	}

	// Initialize Stripe client and monitoring
	stripeClient := stripe.NewStripeClient(cfg.Stripe.SecretKey)
	_ = monitoring.NewStripeMonitor(metrics)
	logger.Info("Stripe client and monitoring initialized")

	// Initialize services
	paymentService := services.NewPaymentService(
		customerRepo,
		subscriptionRepo,
		paymentRepo,
		stripeClient,
	)

	// Initialize HTTP server with database, Redis, and logger
	server := http.NewServer(paymentService, cfg, db.GetDB(), redisClient, logger)

	// Start server
	log.Printf("Payments service starting on %s", cfg.GetServerAddress())
	if err := server.Start(); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}